### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by anikde** [BR903/cgames#10]
ERROR MESSAGE

**command**
make

**output**
 fatal error: gpm.h: No such file or directory
 #include <gpm.h>
          ^~~~~~~
compilation terminated.
<builtin>: recipe for target 'userio.o' failed
make[1]: *** [userio.o] Error 1
make[1]: Leaving directory '/home/anikde/games/cgames-2.2b/cmines'
Makefile:28: recipe for target 'cmines-build' failed
make: *** [cmines-build] Error

**Comment by BR903** [comment]
libgpm is a library for providing a mouse interface in the Linux console. You will need to have libgpm installed with the development files in order to build cmines with mouse support. (On a debian-based system, you would install the `libgpm-dev` package, for example.)

Alternately, you can build all of the programs without mouse support, by including the `--disable-mouse` option
when running `./configure` at the top-level directory.

(Don't forget to check the `README` files for helpful information like this when you run into problems.)

**Comment by anikde** [comment]
thanks a lot.
