### ISSUE TITLE
Failed to install csokoban

### ISSUE THREAD

**Issue by poguepotamus** [BR903/cgames#5]
So I was trying to install the package, the only thing I have different is that the file path (you can see in pastebin) is not the default, not sure if I need to actually change that or not. And I did disable the mouse because I will most likely be using it in tty6. Heres the pastebin! http://pastebin.com/j6t1GAdZ Thanks to anyone who can give me some answers.

**Comment by BR903** [comment]
> install: cannot change permissions of ?/usr/local/games?: Operation not permitted

Yes, typically only root has write permissions to directories under
/usr/local/*. You need to run the install command via sudo.

**Comment by alexgibbs606** [comment]
Thanks :) I'm newer to programming, it still surprises me how easily you can miss something so simple. I've noticed that sokoban and blocks require me to run it in my tty terminals. Is this due to me compiling without the mouse support? Its not much a problem beuause thats where I planned on running them anyway, but I am curious. 
Thanks for the great games, I plan on using it for time between my university classes!
